### ISSUE TITLE
Dependency from @babel/traverse@7.22.8

### ISSUE THREAD

**Issue by felipesanti** [davidedantonio/fastify-axios#32]
Please look at this new [vulnerability](https://github.com/advisories/GHSA-67hx-6x53-jw92)

Auditing my Fastify project, it looks like the dependency is indeed on `fastify-axios`

```
└─┬ fastify-axios@1.2.6
  └─┬ tap@16.3.9
    ├─┬ @isaacs/import-jsx@4.0.1
    │ └─┬ @babel/core@7.22.9
    │   ├─┬ @babel/helpers@7.22.6
    │   │ └── @babel/traverse@7.22.8 deduped
    │   └── @babel/traverse@7.22.8
```

Could you please fix the dependency?

**Comment by davidedantonio** [comment]
Fixed with version 1.2.8
