### ISSUE TITLE
Dependency on axios version with vulnerability

### ISSUE THREAD

**Issue by DanCRichards** [davidedantonio/fastify-axios#40]
This repository has a dependency on the axios@1.6.2 which has a dependency on the follow-redirects@1.15.3 package which has a vulnerability which has improper input validation which is can be maliciously cause a user to redirect traffic to a malicious site. 

Merging this PR would be beneficial please. 
https://github.com/davidedantonio/fastify-axios/pull/39/commits

**Comment by DanCRichards** [comment]
Thank you so much for your effort in developing this open source software, if others haven't said it I am appreciative of your work. 

Dan - Sydney, Australia.

**Comment by davidedantonio** [comment]
Hi @DanCRichards! Thank you for your pull request. 🙏 
I've updated the dependencies!

**Comment by DanCRichards** [comment]
You legend. 

Closing this issue.
